version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Use the appropriate Java version (e.g., corretto8, corretto11, corretto17)
    commands:
      - echo "Installing dependencies..."
      - mvn install

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - mvn clean

  build:
    commands:
      - echo "Building the Java project..."
      - mvn package
      - echo "Running tests..."
      - mvn test

  post_build:
    commands:
      - echo "Post-build phase completed."

artifacts:
  files:
    - target/*.jar # Adjust this if your JAR has a specific name
  discard-paths: yes
